//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ITEM_ID { get; set; }
        public int TODO_LIST_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DEADLINE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int STATUS { get; set; }
    
        public virtual TODO_LIST TODO_LIST { get; set; }
    }
}
