//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODO_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TODO_LIST()
        {
            this.ITEMs = new HashSet<ITEM>();
        }
    
        public int TODO_LIST_ID { get; set; }
        public int USER_ID { get; set; }
        public string TODO_LIST_NAME { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMs { get; set; }
        public virtual USER USER { get; set; }
    }
}
